//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trainer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropsEmployee
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> PropsId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Props Props { get; set; }
    }
}
