//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_MANAGER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Props
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Props()
        {
            this.PropsEmployee = new HashSet<PropsEmployee>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypePropsId { get; set; }
        public byte[] Image { get; set; }
    
        public virtual TypeProps TypeProps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropsEmployee> PropsEmployee { get; set; }
    }
}
